### PR TITLE
fix(test): small fixes and facelift

### LINKED ISSUE #45247: Challenge (Use the .env File) delete the property instead of setting it to undefined
Technically, if we are testing for a non-existing property we can't set `process.env.MESSAGE_STYLE` to `undefined` as that is implicitly converted to a string.

> [process.env](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_process_env)
> 
> Assigning a property on process.env will implicitly convert the value to a string.

This means you can't use this logic

```
// process.env.MESSAGE_STYLE = 'uppercase'

let message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}

console.log(message) // { message: 'HELLO JSON' }

process.env.MESSAGE_STYLE = undefined;
console.log(typeof process.env.MESSAGE_STYLE) // string

message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}
console.log(message) // { message: 'HELLO JSON' }
```

But if you delete it, it works.

```
delete process.env.MESSAGE_STYLE
message = process.env.MESSAGE_STYLE ? {"message": "HELLO JSON"} : {"message": "Hello json"}
console.log(message) // { message: 'Hello json' }
```

The forum thread that made me open this issue:

https://forum.freecodecamp.org/t/use-the-end-file/498485

---

Challenge: https://www.freecodecamp.org/learn/back-end-development-and-apis/basic-node-and-express/use-the--env-file

Test: https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/master/index.js

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/45247

I was going to fix an issue with how we are setting `MESSAGE_STYLE` in the test but then I thought I might as well update this just a bit.

1. `delete` the property `MESSAGE_STYLE` instead of setting it to `undefined`. This is the main point of this PR. Properties set on process.env are explicitly converted to strings, i.e. `undefined` becomes `"undefined"` and not a falsy value as a non-existing property would be.

2. Tiny bit of code cleanup and variables updated to `const` and/or `let`.

3. Updated `package.json` and gave it a version bump. Small update to README (nothing much).

Tested locally and online on Replit with all tests passing using code from a project that was previously passing.

I will admit testing this is a bit tedious and I might have missed something as I didn't thoroughly test for failing tests. But I don't think I broke anything (fingers crossed).

Here is a Replit with the updated lib code pulled from my GitHub
https://replit.com/@lasjorg/fCC-boilerplate-express-test-lib-code

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -66,44 +66,48 @@ function setupBackgroundApp(app, myApp, dirname) {
...
   app.get('/_api/use-env-vars', function (req, res, next) {
-    var foundVar = process.env.MESSAGE_STYLE === 'uppercase';
-    if (!foundVar) return res.json({ passed: false });
-    var envvar = process.env.MESSAGE_STYLE;
-    process.env.MESSAGE_STYLE = undefined;
+    const MESSAGE_STYLE = process.env.MESSAGE_STYLE;
+    if (MESSAGE_STYLE !== 'uppercase') return res.json({ passed: false });
+
+    let lowerCaseMessage, upperCaseMessage;
+    delete process.env.MESSAGE_STYLE;
```
Comment (ShaunSHamilton) [inline index.js]:
```suggestion
    process.env.MESSAGE_STYLE = 'othercase';
```

**Review by naomi-lgbt — APPROVED** [review]
This should be good to go, I think.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 

Thank you, Lasse.
