### PR TITLE
fix(pkg): Add User-Agent to headers

### LINKED ISSUE #2: Unable to complete the ".env" exercise due to errors in the module.
**Unable to complete the ".env" exercise, due to some error in this node module.**

Every time I submit my solution on the fcc exercise (https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file/) the below error is shown in the logs on the glitch.me portal.

Error Screenshot:
Screen Shot 2019-05-08 at 12 14 22 PM

But if I refresh the URL on the glitch.me portal, the error is gone.
Screenshot:
Screen Shot 2019-05-08 at 12 20 56 PM

Hope this is an issue as I'm able to run the program on the local machine without any errors.

### LINKED ISSUE #3: Unable to validate "Use the .env File" lesson due code error
Even thought I'm following the steps as it is indicated I'm unable to pass the lesson. The code is failing on this line because it is making reference to the next function which is clearly not defined.

https://github.com/freeCodeCamp/fcc-express-bground-pkg/blob/597d66d2cc536e746e1603d0332246317d515f79/index.js#L66

This is the glitch that validates the error: https://glitch.com/edit/#!/incandescent-bottlenose-harbor

### LINKED ISSUE #4: in JSON at position 0
The site had old version of bowser, so  the use env goal fail.
<script src="https://cdnjs.cloudflare.com/ajax/libs/bowser/1.9.4/bowser.min.js"></script>

jquery.min.js:4 GET https://atom-earthworm.glitch.me/_api/use-env-vars 500
send @ jquery.min.js:4
ajax @ jquery.min.js:4
r.<computed> @ jquery.min.js:4
eval @ VM77:1
evalTest @ main.js:113
runTest @ main.js:80
(anonymous) @ main.js:170
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
main.js:146 Unexpected token < in JSON at position 0 Error: Unexpected token < in JSON at position 0
    at Object.eval (eval at evalTest (https://narrow-plane.glitch.me/main.js:101:14), <anonymous>:1:199)
    at j (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29568)
    at k (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:29882)

### PR DESCRIPTION
**Pull request by lasjorg**
This PR should (potentially) fix an issue with Glitch we are seeing where the request function gets a 403 and is redirected to a page with the title Maintenance. This causes the res.json to send HTML instead of JSON.

I have not yet had anybody else give confirmation of this fix because Glitch is really unstable right now. I would just like to get this PR made now anyway. Also, I just chose some random user-agent string, not sure what the best option is.

The diff is a little noisy because of the prettier formatting, the PR change is on lines 26-29 in index.js

Closes #2, closes #3, and closes #4

More info here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/39095

Here is a starter project with the change added to the dependencies (dependency link is to my own repo)
https://glitch.com/edit/#!/basic-node-and-express-challenges-with-new-pkg

### CODE REVIEW

**Comment by RandellDawson** [comment]
@lasjorg Should this fix issue #3 and #4 in this repo?

**Comment by lasjorg** [comment]
@RandellDawson Technically yes, but those issues are listing reasons that are not actually breaking the challenge (#3 next missing from the parameters, #4 bowser version < 2 on the redirect page).

I can add them to the PR closes issues if you want?

Edit: I added them to the OP, all open issues on this repo should be fixed with this PR.

**Comment by ShaunSHamilton** [comment]
Hey, lasjorg. How did you choose/find that specific user agent?

**Comment by lasjorg** [comment]
@Sky020 It's just some random one I found in the examples of this npm package.
https://www.npmjs.com/package/user-agents

I initially used Postman's user-agent and when that worked I just picked a more common one.

**Comment by ojeytonwilliams** [comment]
@lasjorg Glitch is still having issues talking to its api, so I can't confirm this yet.  

As for the noise, don't worry about it for this PR, but you can split the formatting into a separate commit, so that reviewers can ignore it.

**Comment by lasjorg** [comment]
We are getting a lot of forum posts about this issue. Can nobody confirm this fix? I'd like to get this merged so we can see if it helps or not.

@RandellDawson @Sky020 @ojeytonwilliams (is there somebody else I should ping here?)

Here is the link for the .env challenge:
https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the-.env-file

Here is the project with the fix from this PR in the dependency. Just paste it in the for the solution, it should pass (the project has to wake up first).
https://basic-node-and-express-challenges-with-new-pkg.glitch.me

And just for reference here is a project that has the exact same code for the solution, but without the PR fix, it should fail.
https://lasjorg-fcc-node-and-express.glitch.me/

I also updated the OP with the link to the project in editor mode. I added the normal full page link by mistake.

**Comment by ShaunSHamilton** [comment]
Sorry about the delay. You are right - we should get this moving, as many are encountering the issue.

From what I have been able to see, your solution does solve the issue. I am interested in why this is/all-of-a-sudden became an issue with Glitch, though...

File: index.js [hunk 1]
```diff
@@ -14,53 +13,65 @@ var globals = require('./globals');
...
-    selfCaller('/json', req, res, function(lowerCase, req, res) {
+    selfCaller('/json', req, res, function (lowerCase, req, res) {
       process.env.MESSAGE_STYLE = msgStyle;
       try {
         lowerCase = JSON.parse(lowerCase);
-      } catch(e) {
+      } catch (e) {
         console.log(e);
         process.env.MESSAGE_STYLE = msgStyle;
         next(e);
```
Comment (ShaunSHamilton) [inline index.js:77]: I am not entirely familiar with the working of this function, but as mentioned in another issue, `next()` either needs to be passed to be used here, or this line needs to be removed.

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
Once, this gets resolved, I would approve.

File: index.js (hunk 1 above)
Comment (lasjorg) [reply index.js:77]: I guess it's fine to fix it in this PR. Done.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Comment by lasjorg** [comment]
> I am interested in why this is/all-of-a-sudden became an issue with Glitch, though...

I can't say for sure but the blocking of [pinging services](https://support.glitch.com/t/ping-service-block-june-13-7-56-a-m-to-present/26443) might somehow [be related](https://support.glitch.com/t/glitch-app-to-glitch-app-403s/26551). It should be temporary as far as I can tell from reading the forum a bit, but there is no ETA on when they will unblock.

Edit: The Glitch team has decided to block pinging services permanently
https://glitch.com/glimmer/post/ping-services

**Comment by lasjorg** [comment]
Can someone please merge this PR?

File: index.js (hunk 1 above)
Comment (ojeytonwilliams) [reply index.js:77]: It's fine, I just won't squash the commits.

Comment (ojeytonwilliams) [reply index.js:77]: So, this is kinda weird, because it seems to be passing around stuff that's already available via closure.  I think it's fine, just confusingly written.

**Comment by ojeytonwilliams** [comment]
Really nice job @lasjorg.  I was finally able to test it out and it worked beautifully.

The change *should* be live now, but there may be some caching issues, so I'll try again later.

**Comment by lasjorg** [comment]
@ojeytonwilliams Thank you for the merge. It works for me. I did have to remove the dependency and add it back to get the new version.

---

Side note: I forgot that I wanted to remove the `engines` property from package.json. I don't think it makes any sense to have it as Glitch just ignores it anyway (terminal message: Could not find node 4.4.5, using 10) and it's such an old node version. I'm not sure if it really matters, but we might as well remove the property. I might make a new PR at some point just to get it done.

**Comment by ojeytonwilliams** [comment]
> I did have to remove the dependency and add it back to get the new version.

Me too.  It should work for new users, though.

Regarding the engines, I think it can matter, since there can be breaking changes between node versions and it seems Glitch relies on `engines` when deciding which node version to use.  Described [here](https://glitch.com/help/node/).  Setting it to `12.0.0` seems like the best future proofing.
